export const APP_LOADING_REQUEST = 'APP_LOADING_REQUEST';

export const APP_LOADING_SUCCESS = 'APP_LOADING_SUCCESS';

export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';

export const ERROR_OCCURRED = 'ERROR_OCCURRED';

export const ERROR_HIDDEN = 'ERROR_HIDDEN';
